server:
  port: 8002
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  type-aliases-package: com.wjj.springcloud.api.entity
  mapper-locations: classpath:mybatis/mapper/**/*.xml
spring:
  application:
    name: springcloudprovider
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sunits2?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT&useSSL=false
    username: root
    password: 1234
eureka:
  client:
    service-url:
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: springcloud_provider_dept2 #自定义服务显示名称
    prefer-ip-address: true #访问路径显示IP
info:
  app.name: springcloud
  company.name: www.wjj.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$