server:
  port: 9527
spring:
  application:
    name: springcloudzuul
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: springcloud_zuul #自定义服务显示名称
    prefer-ip-address: true #访问路径显示IP
info:
  app.name: springcloud
  company.name: www.wjj.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$