server:
  port: 8001
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  type-aliases-package: com.wjj.springcloud.api.entity
  mapper-locations: classpath:mybatis/mapper/**/*.xml
spring:
  application:
    name: springcloud_provider
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sunits?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT&useSSL=false
    username: root
    password: 1234
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: springcloud_provider_dept #自定义服务显示名称
    prefer-ip-address: true #访问路径显示IP